"use client";
import { SideBar } from "@/components/nav/SideBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Heading } from "@/components/nav/Heading";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Yajat Chaudhary | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <Heading />
        {children}
      </body>
    </html>
  );
}
