import "./globals.css";
import { Catamaran } from "next/font/google";

const catamaran = Catamaran({
  weight: ["200","300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Yajat Chaudhary | Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={catamaran.className}>{children}</body>
    </html>
  );
}
